const vehicles=[
{id:1,brand:'Jeep',model:'Compass Limited',year:2022,type:'SUV',km:'42.300 km',price:154.9,image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85',badge:'Destaque',fuel:'Flex',gear:'Automático',color:'Cinza grafite'},
{id:2,brand:'Toyota',model:'Corolla XEi',year:2021,type:'Sedan',km:'38.100 km',price:119.9,image:'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=85',badge:'Único dono',fuel:'Flex',gear:'Automático',color:'Prata'},
{id:3,brand:'Volkswagen',model:'T-Cross Highline',year:2023,type:'SUV',km:'21.800 km',price:138.5,image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=85',badge:'Oferta',fuel:'Flex',gear:'Automático',color:'Branco'},
{id:4,brand:'Honda',model:'Civic Touring',year:2020,type:'Sedan',km:'56.900 km',price:144.9,image:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=85',badge:'',fuel:'Gasolina',gear:'Automático',color:'Preto'},
{id:5,brand:'Chevrolet',model:'Onix Premier',year:2022,type:'Hatch',km:'31.500 km',price:82.9,image:'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85',badge:'Oferta',fuel:'Flex',gear:'Automático',color:'Vermelho'},
{id:6,brand:'Ford',model:'Ranger Limited',year:2021,type:'Picape',km:'64.200 km',price:189.9,image:'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=900&q=85',badge:'',fuel:'Diesel',gear:'Automático',color:'Branco'}];
const grid=document.querySelector('#vehicleGrid'),empty=document.querySelector('#emptyState');let activeCategory='all';
function money(v){return 'R$ '+v.toFixed(1).replace('.',',')+' mil'}
function render(){const q=document.querySelector('#searchInput').value.toLowerCase(),type=document.querySelector('#typeFilter').value,cap=document.querySelector('#priceFilter').value,sort=document.querySelector('#sortFilter').value;let data=vehicles.filter(v=>(activeCategory==='all'||v.type===activeCategory)&&(type==='all'||v.type===type)&&(!cap||v.price<=Number(cap))&&(`${v.brand} ${v.model}`.toLowerCase().includes(q)));if(sort==='lower')data.sort((a,b)=>a.price-b.price);if(sort==='higher')data.sort((a,b)=>b.price-a.price);grid.innerHTML=data.map(v=>`<article class="vehicle-card" data-id="${v.id}"><div class="vehicle-image"><img src="${v.image}" alt="${v.brand} ${v.model}">${v.badge?`<span class="badge">${v.badge}</span>`:''}<button class="heart" data-heart="${v.id}" aria-label="Favoritar veículo">♡</button></div><div class="vehicle-info"><div class="vehicle-title"><h3>${v.brand} ${v.model}</h3><span class="vehicle-year">${v.year}</span></div><p class="vehicle-sub">${v.type} · ${v.km}</p><div class="vehicle-meta"><div><span>A partir de</span><strong class="price">${money(v.price)}</strong></div><span class="card-arrow">↗</span></div></div></article>`).join('');empty.style.display=data.length?'none':'block'}
function openModal(v){document.querySelector('#modalContent').innerHTML=`<div class="modal-layout"><img src="${v.image}" alt="${v.brand} ${v.model}"><div class="modal-details"><span class="modal-badge">${v.badge||'Disponível agora'}</span><h2>${v.brand}<br><em>${v.model}</em></h2><p class="vehicle-sub">${v.type} · ${v.year} · ${v.km}</p><div class="detail-list"><div><span>Combustível</span><strong>${v.fuel}</strong></div><div><span>Câmbio</span><strong>${v.gear}</strong></div><div><span>Cor</span><strong>${v.color}</strong></div><div><span>Categoria</span><strong>${v.type}</strong></div></div><div><span class="vehicle-sub">Preço à vista</span><strong class="price">${money(v.price)}</strong></div><a class="btn btn-primary" target="_blank" rel="noreferrer" href="https://wa.me/5511999990000?text=${encodeURIComponent(`Olá! Tenho interesse no ${v.brand} ${v.model} ${v.year}, anunciado por ${money(v.price)}.`)}">Tenho interesse <b>↗</b></a><p class="modal-note">Resposta rápida pelo WhatsApp do vendedor</p></div></div>`;document.querySelector('#modalBackdrop').classList.add('open');document.body.style.overflow='hidden'}
grid.addEventListener('click',e=>{const heart=e.target.closest('[data-heart]');if(heart){e.stopPropagation();heart.classList.toggle('saved');heart.textContent=heart.classList.contains('saved')?'♥':'♡';return}const card=e.target.closest('.vehicle-card');if(card)openModal(vehicles.find(v=>v.id==card.dataset.id))});document.querySelectorAll('.category').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;render()}));['searchInput','typeFilter','priceFilter','sortFilter'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='searchInput'?'input':'change',render));document.querySelector('#clearFilters').onclick=()=>{document.querySelector('#searchInput').value='';document.querySelector('#typeFilter').value='all';document.querySelector('#priceFilter').value='all';document.querySelector('#sortFilter').value='featured';activeCategory='all';document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='all'));render()};document.querySelector('#modalClose').onclick=()=>{document.querySelector('#modalBackdrop').classList.remove('open');document.body.style.overflow=''};document.querySelector('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')document.querySelector('#modalClose').click()};document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#modalClose').click()});render();
